#%RAML 1.0 NamedExample
value:
    airlineName: "Delta"
    code: "A1B2C4"
    departureDate: "2015/02/11"
    destination: "LAX"
    emptySeats: "10"
    origin: "MUA"
    planeType: "Boing 737"
    price: "199.99"
    IsoCode: "LA"
    PhoneCode: "856"
    Name: "Laos"
    sCapitalCity: "Vientiane"
    ContinentCode: "AS"
        